config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'dashboard/index', as: 'dashboard'

  get 'player/:platform/:username' => 'player#show', as: 'player'
  get 'player/search' => 'player#search', as: 'player_search'
  get 'player/:platform/:username/mode/:mode' => 'player#mode', as: 'player_mode'
  get 'player/:platform/:username/weapon/:weapon' => 'player#weapon', as: 'player_weapon'
  get 'player/:platform/:username/divisions/:division' => 'player#division', as: 'player_division'
end

app/models/player.rb
class Player < ApplicationRecord
  def self.api_get_data(platform, username, title)
    JSON.parse(HTTP.get(Player.api_url(platform, username, title)))
  end

  def self.find_player_or_update(platform, username, title, force_update = false)
    player = Player.find_by(platform: platform, username: username, title: title)
    player_data = Player.api_get_data(platform, username, title) unless player and player.data and !force_update and !player.needs_update?
    return player, nil unless player_data
    return player, false, 'Failed to update player: Bad response' unless player_data['status'] == 'success'
    return player, false, 'Failed to update player: Please wait to update again' if force_update and !player.allowed_update?
    player = Player.new(platform: platform, username: player_data['data']['username'], title: title) unless player
    player.data = player_data['data']
    player.map_weapon_data
    player.save
    return player, true, "#{player.username} successfully updated"
  end

  def self.find_player(platform, username, title)
    player, _, _ = Player.find_player_or_update(platform, username, title, false)
    player
  end

  def allowed_update?
    Time.now >= (updated_at + 15.minutes)
  end

  def needs_update?
    Time.now >= (updated_at + 5.hours)
  end

  def level
    mp_data['level'].to_i
  end

  def prestige
    mp_data['prestige'].to_i
  end

  def kd_ratio(mode = nil, weekly = false)
    return get_mode_data('kdRatio', nil, weekly) unless mode
    ks = kills mode, weekly
    ds = deaths mode, weekly
    return nil unless ks && ds
    kd = ks.to_f / ds.to_f
    kd&.nan? ? nil : kd
  end

  def kills(mode = nil, weekly = false)
    get_mode_data('kills', mode, weekly).to_i
  end

  def deaths(mode = nil, weekly = false)
    get_mode_data('deaths', mode, weekly).to_i
  end

  def win_percentage(mode = nil, weekly = false)
    ws = wins mode, weekly
    ls = losses mode, weekly
    return nil unless ws && ls
    return 1 if ws.nonzero? && ls.zero?
    return nil if ls.zero?
    ws.to_f / (ws + ls).to_f
  end

  def wins(mode = nil, weekly = false)
    get_mode_data('wins', mode, weekly).to_i
  end

  def losses(mode = nil, weekly = false)
    get_mode_data('losses', mode, weekly).to_i
  end

  def best_primary
    data = get_data 'allNonNumerical', false
    return nil unless data
    data['bestPrimary']
  end

  def best_secondary
    data = get_data 'allNonNumerical', false
    return nil unless data
    data['bestSecondary']
    end

  def best_lethal
    data = get_data 'allNonNumerical', false
    return nil unless data
    data['bestLethal']
    end

  def best_tactical
    data = get_data 'allNonNumerical', false
    return nil unless data
    data['bestTactical']
  end

  def best_score_streak_attack
    data = get_data 'allNonNumerical', false
    return nil unless data
    data['bestScorestreakAttack']
    end

  def best_score_streak_support
    data = get_data 'allNonNumerical', false
    return nil unless data
    data['bestScorestreakSupport']
  end

  def mode_score(mode = nil, weekly = false)
    kd = kd_ratio mode, weekly
    win_pct = win_percentage mode, weekly
    spm = score_per_minute mode, weekly
    return nil unless kd && win_pct && spm
    ((kd + (win_pct / 10) + (spm / 1000)) * 1000).to_i
  end

  def score(mode = nil, weekly = false)
    get_mode_data 'score', mode, weekly
  end

  def time_played(mode = nil, weekly = false)
    stat = mode.to_s.start_with?('division:') ? 'timeInUse' : 'timePlayed'
    get_mode_data stat, mode, weekly
  end

  def score_per_minute(mode = nil, weekly = false)
    scr = score mode, weekly
    tp = time_played mode, weekly
    return nil unless scr && tp
    spm = scr / (tp / 60.0)
    spm.nan? ? nil : spm
  end

  def kills_per_minute(mode = nil, weekly = false)
    ks = kills mode, weekly
    tp = time_played mode, weekly
    return nil unless ks && tp
    kpm = ks / (tp / 60.0)
    kpm.nan? ? nil : kpm
  end

  def deaths_per_minute(mode = nil, weekly = false)
    ds = deaths mode, weekly
    tp = time_played mode, weekly
    return nil unless ds && tp
    dpm = ds / (tp / 60.0)
    dpm.nan? ? nil : dpm
  end

  def self.modes
    { dm:       'Free For All',
      hp:       'Hardpoint',
      sd:       'Search & Destroy',
      ctf:      'Capture the Flag',
      dom:      'Domination',
      gun:      'Gun Game',
      war:      'Team Deathmatch',
      ball:     'Gridiron',
      conf:     'Kill Confirmed',
      demo:     'Demolition',
      dm_hc:    'Hardcore Free For All',
      sd_hc:    'Hardcore Search & Destroy',
      dom_hc:   'Hardcore Domination',
      war_hc:   'Hardcore Team Deathmatch',
      conf_hc:  'Hardcore Kill Confirmed' }
  end

  def self.divisions
    { 'division:armored': 'Armored',
      'division:airborne': 'Airborne',
      'division:infantry': 'Infantry',
      'division:mountain': 'Mountain',
      'division:resistance': 'Resistance',
      'division:expeditionary': 'Expeditionary' }
  end

  def mode(mode_name)
    mode_data[mode_name]
  end

  def mode_data
    get_data('mode', false)
  end

  def division(division_name)
    mode_data[division_name]
  end

  def weapon(weapon_name)
    weapon_data[weapon_name]
  end

  def weapon_data
    get_data('weaponData', false)
  end

  def map_weapon_data
    weapon_data&.each do |weap_name, weap_data|
      weapon_type, weapon_class = Player.weapon_map weap_data['label']
      weapon_data[weap_name]['weapon_type'] = weapon_type
      weapon_data[weap_name]['weapon_class'] = weapon_class
    end
  end

  def weapon_type_data(weapon_type)
    weapons = weapon_data&.select { |_, data|
      data['weapon_type'] == weapon_type.to_s
    }
    return nil unless weapons
    kills = 0
    deaths = 0
    multikills = 0
    time_in_use = 0
    time_in_use = 0
    shots = 0
    hits = 0
    weapons.each do |_, weapon_data|
      kills += weapon_data['kills']
      deaths += weapon_data['deaths']
      multikills += weapon_data['multikills']
      time_in_use += weapon_data['timeInUse']
      hits += weapon_data['hits']
      shots += weapon_data['shots']
    end
    {
      kills: kills,
      deaths: deaths,
      multikills: multikills,
      time_in_use: time_in_use,
      hits: hits,
      shots: shots
    }
  end

  def accuracy
    get_mode_data('accuracy', nil, false)
  end

  def hits
    get_mode_data('hits', nil, false)
  end

  def misses
    get_mode_data('misses', nil, false)
  end

  def last_played
    last_game = 0
    Player.modes.each do |mode, _|
      mode_last_game = get_mode_data 'timeStampLastGame', mode, false
      last_game = mode_last_game if last_game < mode_last_game
    end
    last_game
  end

  def platform_long
    return 'playstation'  if platform == 'psn'
    return 'xbox'         if platform == 'xbl'
    return 'steam'        if platform == 'steam'
  end

  private

  def mp_data
    data['mp']
  end

  def lifetime_mp_data
    mp_data['lifetime']
  end

  def weekly_mp_data
    mp_data['weekly']
  end

  def get_mode_data(stat, mode, weekly)
    data = get_data('all', weekly)
    return nil if data.none?
    return data[stat] unless mode
    data = get_data('mode', weekly)
    return nil unless data
    data_mode = data[mode.to_s]
    data_mode[stat] if data_mode
  end

  def get_data(data_name, weekly)
    data = weekly ? weekly_mp_data : lifetime_mp_data
    return nil unless data
    data[data_name]
  end

  def self.api_url(platform, username, title)
    "https://my.callofduty.com/api/papi-client/crm/cod/v2/title/#{title}/platform/#{platform}/gamer/#{username}/profile/"
  end

  def self.weapon_map(weapon)
    data = Player.weapons[:"#{weapon}"]
    [data[:type], data[:class]] if data
  end

  def self.weapons
    {
      'BAR': { type: 'rifle', class: 'primary' },
      '1191': { type: 'pistol', class: 'secondary ' },
      'Bren': { type: 'light_machine_gun', class: 'primary' },
      'GPMG': { type: 'light_machine_gun', class: 'primary' },
      'M-38': { type: 'submachine_gun', class: 'primary' },
      'Orso': { type: 'submachine_gun', class: 'primary' },
      'P-08': { type: 'pistol', class: 'secondary' },
      'Sten': { type: 'submachine_gun', class: 'primary' },
      'FG 42': { type: 'rifle', class: 'primary' },
      'Lewis': { type: 'light_machine_gun', class: 'primary' },
      'M1903': { type: 'sniper_rifle', class: 'primary' },
      'M1928': { type: 'submachine_gun', class: 'primary' },
      'M1941': { type: 'rifle', class: 'primary' },
      'MG 15': { type: 'light_machine_gun', class: 'primary' },
      'MG 42': { type: 'light_machine_gun', class: 'primary' },
      'MG 81': { type: 'light_machine_gun', class: 'primary' },
      'MP-40': { type: 'submachine_gun', class: 'primary' },
      'STG44': { type: 'rifle', class: 'primary' },
      'Kar98k': { type: 'sniper_rifle', class: 'primary' },
      'SVT-40': { type: 'rifle', class: 'primary' },
      'Type 5': { type: 'rifle', class: 'primary' },
      'ZK-383': { type: 'submachine_gun', class: 'primary' },
      '9mm SAP': { type: 'pistol', class: 'secondary' },
      'Karabin': { type: 'sniper_rifle', class: 'primary' },
      'PPSh-41': { type: 'submachine_gun', class: 'primary' },
      'PTRS-41': { type: 'sniper_rifle', class: 'primary' },
      'Stinger': { type: 'light_machine_gun', class: 'primary' },
      'Type 38': { type: 'sniper_rifle', class: 'primary' },
      'Claymore': { type: 'melee', class: 'secondary' },
      'Fire Axe': { type: 'melee', class: 'secondary' },
      'Ice Pick': { type: 'melee', class: 'secondary' },
      'Sterling': { type: 'submachine_gun', class: 'primary' },
      'Type 100': { type: 'submachine_gun', class: 'primary' },
      'Waffe 28': { type: 'submachine_gun', class: 'primary' },
      'Gewehr 43': { type: 'rifle', class: 'primary' },
      'M1 Garand': { type: 'rifle', class: 'primary' },
      'US Shovel': { type: 'melee', class: 'secondary' },

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def show
    @player, update_successful, update_message = Player.find_player_or_update(params[:platform], params[:username], 'wwii', params[:force_update])
    unless @player
      redirect_back(fallback_location: root_path, flash: { danger: "Player \"#{params[:username]}\" not found" }) and return
    end
    if update_successful
      flash.now[:success] = update_message
    elsif !update_successful.nil? and !update_successful
      flash.now[:danger] = update_message
    end
  end

  def search
    params = player_params
    redirect_to player_path(params[:platform], params[:username])
  end

  def mode
    @player = Player.find_player params[:platform], params[:username], 'wwii'
    @mode = @player.mode mode_params
  end

  def weapon
    @player = Player.find_player params[:platform], params[:username], 'wwii'
    @weapon = @player.weapon weapon_params
  end

  def division
    @player = Player.find_player params[:platform], params[:username], 'wwii'
    @division = @player.division division_params
  end

  private

  def player_params
    params.require :platform
    params.require :username
    params.permit :force_update, :platform, :username
  end

  def mode_params
    params.require :mode
  end

  def weapon_params
    params.require :weapon
  end

  def division_params
    params.require :division
  end
end

app/helpers/player_helper.rb
module PlayerHelper
  def stat_class(stat, low, high = nil)
    return 'default' unless stat
    high ||= low
    stat = stat.to_f
    if stat == high
      'info'
    elsif stat <= low
      'danger'
    elsif stat >= high
      'success'
    else
      'warning'
    end
  end

  def stat_direction(stat, lifetime_stat)
    return nil unless stat && lifetime_stat
    return nil if stat == lifetime_stat
    return 'stat-up' if stat > lifetime_stat
    return 'stat-down' if stat < lifetime_stat
  end

  def percentage(stat)
    stat.to_f * 100 if stat
  end

  def weapon_accuracy(hits, shots)
    return nil if shots.zero?
    (hits / (hits + shots.to_f)) * 100
  end

  def stat_per_minute(stat, time_in_seconds)
    stat / (time_in_seconds / 60.0) unless time_in_seconds.zero?
  end

  def weapon_kd_ratio(kills, deaths)
    return kills if deaths.zero?
    kills / deaths.to_f
  end

  def level_image(player)
    level = player.level
    prestige = player.prestige
    return prestige_img_url prestige.to_i if prestige.nonzero?
    case level
    when 1...40   then level = (level / 3.to_f).ceil
    when 40...50  then level = (((((level - 40) + 1.01) / 3) + level) / 3).ceil
    when 50..55   then level -= 31
    end
    level_img_url level.to_i
  end

  def friendly_platform(platform)
    case platform
    when 'psn' then 'PlayStation'
    when 'xbl' then 'Xbox'
    when 'steam' then 'Steam'
    end
  end

  private

  def prestige_img_url(prestige)
    "https://my.callofduty.com/content/dam/atvi/callofduty/mycod/common/player-icons/wwii/prestige-#{prestige}.png"
  end

  def level_img_url(level)
    "https://my.callofduty.com/content/dam/atvi/callofduty/mycod/common/player-icons/wwii/level-#{level}.png"
  end
end

app/views/player/_divisions.html.erb
<div class="mb-3">
  <div class="full-width">
    <div class="nav nav-tabs mb-4" role="tablist">
      <div class="container">
        <div class="row">
          <h5 class="nav-item nav-text">Divisions</h5>
        </div>
      </div>
    </div>
  </div>
  <div class="tab-content">
    <div class="tab-pane animated table-responsive show active" id="division_data" role="tabpanel" aria-labelledby="division_data-tab">
      <table class="table mb-0">
        <thead>
        <tr>
          <th>Division</th>
          <th>Kills</th>
          <th>Deaths</th>
          <th>KPM</th>
          <th>DPM</th>
          <th>Ratio</th>
        </tr>
        </thead>
        <tbody>
        <% Player.divisions.each do |division, name| %>
          <% kd = @player.kd_ratio(division) %>
          <% next unless kd %>
          <tr>
            <td><%= link_to name, player_division_path(division: division) %></td>
            <td><%= @player.kills division %></td>
            <td><%= @player.deaths division %></td>
            <td><%= number_with_precision(@player.kills_per_minute(division), precision: 1) %></td>
            <td><%= number_with_precision(@player.deaths_per_minute(division), precision: 1) %></td>
            <td class="table-<%= stat_class(kd, @player.kd_ratio(nil)) %>"><%= number_with_precision(kd, precision: 3) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/player/_modes.html.erb
<% data_sets = %w[lifetime weekly] %>

<div class="mb-3">
  <%= render partial: 'shared/tabs', locals: {data_sets: data_sets} %>
  <div class="tab-content">
    <% data_sets.each_with_index do |data_set, index| %>
      <% weekly = data_set == 'weekly' %>
      <div class="tab-pane animated table-responsive show <%= index.zero? ? 'active' : '' %>" id="<%= data_set %>" role="tabpanel" aria-labelledby="<%= data_set %>-tab">
        <table class="table mb-0">
          <thead>
          <tr>
            <th>Mode</th>
            <th>Wins</th>
            <th>Losses</th>
            <th>Win%</th>
            <th>SPM</th>
            <th>Kills</th>
            <th>Deaths</th>
            <th>Ratio</th>
            <th>Score</th>
          </tr>
          </thead>
          <tbody>
          <% Player.modes.each do |mode, name| %>
            <% ms = @player.mode_score mode, weekly %>
            <% next unless ms  %>
            <% wp = @player.win_percentage mode, weekly %>
            <% spm = @player.score_per_minute mode, weekly %>
            <% kd = @player.kd_ratio mode, weekly %>
            <tr>
              <td><%= link_to name, player_mode_path(mode: mode) %></td>
              <td><%= @player.wins mode, weekly %></td>
              <td><%= @player.losses mode, weekly %></td>
              <td class="<%= stat_direction(wp, @player.win_percentage(mode)) %> table-<%= stat_class(wp, 0.5, 0.75) %>"><%= number_with_precision(percentage(wp), precision: 1) %></td>
              <td class="<%= stat_direction(spm, @player.score_per_minute(mode)) %> table-<%= stat_class(spm, @player.score_per_minute(nil, weekly)) %>"><%= number_with_precision(spm, precision: 1) %></td>
              <td><%= @player.kills mode, weekly %></td>
              <td><%= @player.deaths mode, weekly %></td>
              <td class="<%= stat_direction(kd, @player.kd_ratio(mode)) %> table-<%= stat_class(kd, @player.kd_ratio(nil, weekly)) %>"><%= number_with_precision(kd, precision: 3) %></td>
              <td class="<%= stat_direction(ms, @player.mode_score(mode)) %> table-<%= stat_class(ms, @player.mode_score(nil, weekly)) %>"><%= ms %></td>
            </tr>
          <% end %>
          <tr>
            <% wp = @player.win_percentage nil, weekly %>
            <% spm = @player.score_per_minute nil, weekly %>
            <% kd = @player.kd_ratio nil, weekly %>
            <% ms = @player.mode_score nil, weekly %>
            <th>Overall</th>
            <th><%= @player.wins nil, weekly%></th>
            <th><%= @player.losses nil, weekly %></th>
            <th class="<%= stat_direction(wp, @player.win_percentage) %>"><%= number_with_precision(percentage(wp), precision: 1) %></th>
            <th class="<%= stat_direction(spm, @player.score_per_minute) %>"><%= number_with_precision(spm, precision: 1) %></th>
            <th><%= @player.kills nil, weekly %></th>
            <th><%= @player.deaths nil, weekly %></th>
            <th class="<%= stat_direction(kd, @player.kd_ratio) %>"><%= number_with_precision(kd, precision: 3) %></th>
            <th class="<%= stat_direction(ms, @player.mode_score) %>"><%= ms %></th>
          </tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/player/_public.html.erb
<div class="py-4">
  <div class="row">
    <div class="col-12 col-md-3">
      <div class="text-center">
        <%= image_tag level_image(@player), style: 'max-height: 150px;' %>
        <h4 class="text-muted m-0">Level <%= @player.level %></h4>
      </div>
    </div>
    <div class="col-12 col-md-3">
      <canvas id="kdChart"></canvas>
    </div>
    <div class="col-12 col-md-3">
      <canvas id="wpChart"></canvas>
    </div>
    <div class="col-12 col-md-3">
      <canvas id="accChart"></canvas>
    </div>
  </div>
  <script>
    Chart.defaults.doughnut.maintainAspectRatio = false;
    Chart.defaults.doughnut.cutoutPercentage = 75;
    Chart.defaults.doughnut.legend.display = false;
    Chart.defaults.doughnut.tooltips.enabled = false;
    Chart.defaults.doughnut.hover.mode = null;
    Chart.defaults.doughnut.plugins = {
        datalabels: {
            color: '#FFFFFF',
                backgroundColor: ['#00FF00', '#FF0000'],
                borderRadius: 4,
                padding: 5,
                borderWidth: 2,
                borderColor: '#FFFFFF',
                font: {
                weight: 'bolder',
                clip: false
            }
        }
    };


    var kdChart_ctx = document.getElementById("kdChart").getContext('2d');
    var kdChart = new Chart(kdChart_ctx,{
        type: 'doughnut',
        data: {
            datasets: [{
                data: [<%= @player.kills %>, <%= @player.deaths %>],
                backgroundColor: ['#00FF00', '#FF0000']
            }]
        },
        options: {
            plugins: {
                doughnutlabel: {
                    labels: [{
                        text: 'K/D Ratio',
                        font: {
                            size: 30,
                            color: 'grey'
                        }
                    },
                    {
                        text: <%= @player.kd_ratio %>,
                        font: {
                            size: 100
                        },
                    }]
                }
            }
        }
    });

    var wpChart_ctx = document.getElementById("wpChart").getContext('2d');
    var wpChart = new Chart(wpChart_ctx,{
        type: 'doughnut',
        data: {
            datasets: [{
                data: [<%= @player.wins %>, <%= @player.losses %>],
                backgroundColor: ['#00FF00', '#FF0000']
            }]
        },
        options: {
            plugins: {
                doughnutlabel: {
                    labels: [{
                        text: 'Win %',
                        font: {
                            size: 30,
                            color: 'grey'
                        }
                    },
                    {
                        text: '<%= number_with_precision(percentage(@player.win_percentage), precision: 1) %>',
                        font: {
                            size: 110
                        },
                    }]
                }
            }
        }
    });

    var accChart_ctx = document.getElementById("accChart").getContext('2d');
    var accChart = new Chart(accChart_ctx,{
        type: 'doughnut',
        data: {
            datasets: [{
                data: [<%= @player.hits %>, <%= @player.misses %>],
                backgroundColor: ['#00FF00', '#FF0000']
            }]
        },
        options: {
            plugins: {
                doughnutlabel: {
                    labels: [{
                        text: 'Accuracy',
                        font: {
                            size: 30,
                            color: 'grey'
                        }
                    },
                    {
                        text: '<%= @player.accuracy %>',
                        font: {
                            size: 110
                        },
                    }]
                }
            }
        }
    });
  </script>
<!--  <strong>Prestige</strong> <%#= @player.prestige %><br>-->
<!--  <strong>Level</strong> <%#= @player.level %><br>-->
<!--  <strong>Kills</strong> <%#= @player.kills %><br>-->
<!--  <strong>Deaths</strong> <%#= @player.deaths %><br>-->
<!--  <strong>K/D</strong> <%#= @player.kd_ratio %><br>-->
<!--  <strong>Accuracy</strong> <%#= @player.accuracy %><br>-->
<!--  <strong>Wins</strong> <%#= @player.wins %><br>-->
<!--  <strong>Losses</strong> <%#= @player.losses %><br>-->
<!--  <strong>Win %</strong> <%#= number_with_precision(percentage(@player.win_percentage), precision: 1) %><br>-->

<!--  <strong>Time Played</strong> <%#= @player.time_played %><br>-->
<!--  <strong>Score</strong> <%#= @player.score %><br>-->
<!--  <strong>SPM</strong> <%#= number_with_precision @player.score_per_minute, precision: 1 %><br>-->
<!--  <strong>KPM</strong> <%#= number_with_precision @player.kills_per_minute, precision: 2 %><br>-->
<!--  <strong>DPM</strong> <%#= number_with_precision @player.deaths_per_minute, precision: 2 %><br>-->
<!--  <strong>Best Primary</strong> <%#= link_to @player.best_primary['label'], player_weapon_path(weapon: @player.best_primary['name']) %><br>-->
<!--  <strong>Best Secondary</strong> <%#= link_to @player.best_secondary['label'], player_weapon_path(weapon: @player.best_secondary['name']) %><br>-->
<!--  <strong>Best Lethal</strong> <%#= link_to @player.best_lethal['label'], player_weapon_path(weapon: @player.best_lethal['name']) %><br>-->
<!--  <strong>Best Tactical</strong> <%#= link_to @player.best_tactical['label'], player_weapon_path(weapon: @player.best_tactical['name']) %><br>-->
<!--  <strong>Best Score Streak (Attack)</strong> <%#= link_to @player.best_score_streak_attack['label'], player_weapon_path(weapon: @player.best_score_streak_attack['name']) %><br>-->
<!--  <strong>Best Score Streak (Support)</strong> <%#= link_to @player.best_score_streak_support['label'], player_weapon_path(weapon: @player.best_score_streak_support['name']) %><br>-->
</div>

app/views/player/division.html.erb
<% @division.each do |stat, value| %>
  <%= stat %>: <%= value %><br>
<% end %>

app/views/player/mode.html.erb
<%= render 'player/header.html.erb' %>

<%= Player.modes[:"#{@mode}"] %>

app/views/player/show.html.erb
<div class="row">
  <div  class="col-md-12 px-0 px-sm-3">
    <!-- Public data -->
    <%= render partial: 'public' %>
    <!-- Mode data -->
    <%= render partial: 'modes' %>
    <!-- Weapon data -->
    <%= render partial: 'weapons' %>
    <!-- Division data -->
    <%= render partial: 'divisions' %>
  </div>
</div>

app/views/player/weapon.html.erb
<% @weapon.each do |stat, value| %>
  <%= stat %>: <%= value %><br>
<% end %>