config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'dashboard/index', as: 'dashboard'

  get 'player/:platform/:username' => 'player#show', as: 'player'
  get 'player/search' => 'player#search', as: 'player_search'
  get 'player/:platform/:username/mode/:mode' => 'player#mode', as: 'player_mode'
  get 'player/:platform/:username/weapon/:weapon' => 'player#weapon', as: 'player_weapon'
  get 'player/:platform/:username/divisions/:division' => 'player#division', as: 'player_division'
end

app/views/shared/_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-main alert-<%= key %> d-block">
    <div class="container">
      <div class="row">
        <div class="col-12 px-sm-3 px-0">
          <%= value %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">CoD Stats</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Leaderboard</a>
        </li>
      </ul>
      <%= form_tag player_search_path, :method => :get, class: 'form-inline my-2 my-lg-0' do %>
        <div class="input-group">
          <div class="input-group-prepend">
            <%= select_tag(:platform, options_for_select([['psn', 'psn'],['xbl', 'xbl'],['steam','steam']]), class: 'form-control mr-2 pr-3') %>
          </div>
          <%= text_field_tag :username, nil, class: 'form-control', placeholder: 'Player search', id: 'search' %>
          <div class="input-group-append">
            <i class="fas fa-search"></i>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_tabs.html.erb
<div class="full-width">
  <div class="nav nav-tabs mb-4" role="tablist">
    <div class="container">
      <div class="row">
        <h5 class="nav-item nav-text">Modes</h5>
        <% data_sets.each_with_index do |data_set, index| %>
          <a class="nav-item nav-link <%= index.zero? ? 'active' : '' %>" data-toggle="tab" data-index="<%= index %>" data-target="#<%= data_set %>" role="tab" aria-controls="<%= data_set %>" aria-selected="true"><%= data_set.humanize %></a>
        <% end %>
      </div>
    </div>
  </div>
</div>